import prisma from "../../config/prisma";
import { NotFoundError } from "../../utils/errors";
import { logger } from "../../utils/logger";
import { analyzeComment, generateReply, validateReply } from "../ai/ai.service";
import { sendReplyToFacebook } from "../replies/reply.service";
import { evaluateRules } from "../rules/rules.service";
import type {
  GetCommentsInput,
  UpdateCommentStatusInput,
} from "./comment.validation";

export async function getComments(userId: string, filters: GetCommentsInput) {
  const { pageId, status, limit = 20, offset = 0 } = filters;

  const where: any = {
    facebookPage: {
      userId,
    },
  };

  if (pageId) {
    where.facebookPageId = pageId;
  }

  if (status) {
    where.status = status;
  }

  const [comments, total] = await Promise.all([
    prisma.comment.findMany({
      where,
      include: {
        facebookPage: {
          select: {
            pageId: true,
            pageName: true,
          },
        },
        replies: {
          orderBy: {
            createdAt: "desc",
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
      take: limit,
      skip: offset,
    }),
    prisma.comment.count({ where }),
  ]);

  const formattedComments = comments.map((comment) => ({
    ...comment,
    facebookCommentId: comment.commentId,
    content: comment.userMessage,
    authorName: comment.userName || "Unknown",
    authorId: comment.userId,
    pageId: comment.facebookPageId,
    page: comment.facebookPage,
    reply: comment.replies?.[0]
      ? {
          ...comment.replies[0],
          content: comment.replies[0].generatedReply,
          aiConfidence: comment.replies[0].confidence,
          isAutoGenerated: true,
        }
      : undefined,
  }));

  return {
    comments: formattedComments,
    total,
    limit,
    offset,
  };
}

export async function getCommentById(userId: string, commentId: string) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
    include: {
      facebookPage: {
        select: {
          pageId: true,
          pageName: true,
        },
      },
      replies: {
        orderBy: {
          createdAt: "desc",
        },
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  return comment;
}

export async function updateCommentStatus(
  userId: string,
  commentId: string,
  data: UpdateCommentStatusInput,
) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  const updated = await prisma.comment.update({
    where: { id: commentId },
    data: {
      status: data.status,
    },
  });

  logger.info(
    { userId, commentId, status: data.status },
    "Comment status updated",
  );

  return updated;
}

export async function processComment(commentId: string) {
  const comment = await prisma.comment.findUnique({
    where: { id: commentId },
    include: {
      facebookPage: true,
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  // Check if comment is already processed
  if (comment.status !== "PENDING") {
    logger.info(
      { commentId, status: comment.status },
      "Comment already processed",
    );
    return comment;
  }

  // Get AI settings for the user (or create defaults)
  let aiSettings = await prisma.aISettings.findUnique({
    where: { userId: comment.facebookPage.userId },
  });

  if (!aiSettings) {
    aiSettings = await prisma.aISettings.create({
      data: {
        userId: comment.facebookPage.userId,
        status: "ACTIVE",
        aiProvider: "openrouter",
        model: "google/gemma-4-31b-it:free",
        confidenceThreshold: 0.7,
        tone: "professional",
        language: "en",
        emojiUsage: true,
        maxLength: 500,
        spamHandling: "ignore",
        humanApprovalMode: false,
        fallbackBehavior: "skip",
      },
    });
    logger.info({ userId: comment.facebookPage.userId }, "Created default AI settings");
  }

  if (aiSettings.status !== "ACTIVE") {
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "IGNORED" },
    });
    logger.info({ commentId }, "AI not enabled, comment ignored");
    return comment;
  }

  try {
    // 1. Check custom reply rules first
    const matchingRule = await evaluateRules(
      comment.userMessage,
      comment.facebookPage.userId,
    );

    if (matchingRule) {
      logger.info(
        { commentId, ruleId: matchingRule.id, action: matchingRule.action },
        "Matching rule found for comment",
      );

      if (matchingRule.action === "IGNORE") {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "IGNORED" },
        });
        return comment;
      }
    }

    // 2. Analyze comment with AI
    const analysis = await analyzeComment(comment.userMessage, aiSettings);

    // Update comment with AI analysis
    await prisma.comment.update({
      where: { id: commentId },
      data: {
        aiIntent: analysis.intent,
        aiSentiment: analysis.sentiment,
        aiLanguage: analysis.language,
        aiIsSpam: analysis.isSpam,
        aiConfidence: analysis.confidence,
        aiRequiresReview: analysis.requiresHumanReview,
      },
    });

    // 3. Check spam handling
    if (analysis.isSpam && aiSettings.spamHandling === "ignore") {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "IGNORED" },
      });
      logger.info({ commentId }, "Spam detected, comment ignored");
      return comment;
    }

    // 4. Determine reply text (custom rule or AI generation)
    let replyText = "";
    let replyConfidence = analysis.confidence;
    let ruleId: string | null = null;

    if (
      matchingRule &&
      matchingRule.action === "REPLY_CUSTOM" &&
      matchingRule.customReply
    ) {
      replyText = matchingRule.customReply;
      ruleId = matchingRule.id;
      replyConfidence = 1.0;
    } else {
      // Generate reply with AI
      const replyResult = await generateReply(
        comment.userMessage,
        analysis,
        aiSettings,
      );

      // Validate reply
      const isValid = await validateReply(replyResult.reply, aiSettings);
      if (!isValid) {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "ERROR" },
        });
        logger.error({ commentId }, "Generated reply failed validation");
        return comment;
      }

      replyText = replyResult.reply;
      replyConfidence = replyResult.confidence;
    }

    // 5. Determine if human review is required
    // If auto-reply is enabled (humanApprovalMode is false), do NOT block standard comments.
    // Only require human review if the user explicitly enabled requireHumanReview,
    // a rule matched with HUMAN_REVIEW, or severe abuse/negative safety issue was detected.
    let requiresReview = false;
    if (aiSettings.humanApprovalMode) {
      // User explicitly configured "Require Human Review" in Settings
      requiresReview = true;
    } else if (matchingRule?.action === "HUMAN_REVIEW") {
      // A configured rule explicitly triggered human review
      requiresReview = true;
    } else if (analysis.isSpam && aiSettings.spamHandling === "review") {
      requiresReview = true;
    } else if (
      analysis.requiresHumanReview &&
      analysis.sentiment === "negative"
    ) {
      requiresReview = true;
    }

    // 6. Create reply record
    const reply = await prisma.reply.create({
      data: {
        commentId: comment.id,
        facebookPageId: comment.facebookPageId,
        generatedReply: replyText,
        status: requiresReview ? "PENDING" : "APPROVED",
        aiProvider: aiSettings.aiProvider,
        ruleId,
        confidence: replyConfidence,
        requiresHumanReview: requiresReview,
      },
    });

    logger.info(
      { commentId, replyId: reply.id, requiresReview },
      "Reply created in database",
    );

    // 7. Auto-reply to Facebook if human review is NOT required
    if (!requiresReview) {
      try {
        await sendReplyToFacebook(reply.id);
        logger.info(
          { commentId, replyId: reply.id },
          "Auto-reply sent directly to Facebook!",
        );
      } catch (sendError) {
        logger.error(
          { error: sendError, commentId, replyId: reply.id },
          "Auto-reply Facebook send failed",
        );
      }
    } else {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "PENDING" },
      });
      logger.info(
        { commentId, replyId: reply.id },
        "Reply queued for human review in dashboard",
      );
    }

    return comment;
  } catch (error) {
    logger.error({ error, commentId }, "Comment processing failed");
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "ERROR" },
    });
    throw error;
  }
}
