import axios from "axios";
import prisma from "../../config/prisma";
import { NotFoundError } from "../../utils/errors";
import { logger } from "../../utils/logger";
import { analyzeComment, generateReply, validateReply } from "../ai/ai.service";
import { sendReplyToFacebook } from "../replies/reply.service";
import { evaluateRules } from "../rules/rules.service";
import type {
  GetCommentsInput,
  UpdateCommentStatusInput,
} from "./comment.validation";

export async function getComments(userId: string, filters: GetCommentsInput) {
  const { pageId, status, limit = 20, offset = 0 } = filters;

  const where: any = {
    facebookPage: {
      userId,
    },
  };

  if (pageId) {
    where.facebookPageId = pageId;
  }

  if (status) {
    where.status = status;
  }

  const [comments, total] = await Promise.all([
    prisma.comment.findMany({
      where,
      include: {
        facebookPage: {
          select: {
            pageId: true,
            pageName: true,
          },
        },
        replies: {
          orderBy: {
            createdAt: "desc",
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
      take: limit,
      skip: offset,
    }),
    prisma.comment.count({ where }),
  ]);

  const formattedComments = comments.map((comment) => ({
    ...comment,
    facebookCommentId: comment.commentId,
    content: comment.userMessage,
    authorName: comment.userName || "Unknown",
    authorId: comment.userId,
    pageId: comment.facebookPageId,
    page: comment.facebookPage,
    reply: comment.replies?.[0]
      ? {
          ...comment.replies[0],
          content: comment.replies[0].generatedReply,
          aiConfidence: comment.replies[0].confidence,
          isAutoGenerated: true,
        }
      : undefined,
  }));

  return {
    comments: formattedComments,
    total,
    limit,
    offset,
  };
}

export async function getCommentById(userId: string, commentId: string) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
    include: {
      facebookPage: {
        select: {
          pageId: true,
          pageName: true,
        },
      },
      replies: {
        orderBy: {
          createdAt: "desc",
        },
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  return comment;
}

export async function updateCommentStatus(
  userId: string,
  commentId: string,
  data: UpdateCommentStatusInput,
) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  const updated = await prisma.comment.update({
    where: { id: commentId },
    data: {
      status: data.status,
    },
  });

  logger.info(
    { userId, commentId, status: data.status },
    "Comment status updated",
  );

  return updated;
}

/**
 * Stores a comment if it is not already known. Returns null when the comment
 * already exists so callers can skip re-processing it.
 */
export async function storeNewComment(input: {
  commentId: string;
  facebookPageId: string;
  postId: string;
  authorId: string | null;
  authorName: string | null;
  message: string;
  createdTime: Date;
}) {
  const existing = await prisma.comment.findUnique({
    where: { commentId: input.commentId },
  });

  if (existing) {
    return null;
  }

  return prisma.comment.create({
    data: {
      commentId: input.commentId,
      facebookPageId: input.facebookPageId,
      postId: input.postId,
      userId: input.authorId,
      userName: input.authorName,
      userMessage: input.message,
      status: "PENDING",
      createdTime: input.createdTime,
    },
  });
}

/**
 * Pulls recent post comments straight from the Graph API and stores/processes
 * the ones that are missing locally. Keeps the dashboard in sync when webhook
 * deliveries never arrive (app not subscribed, downtime, development mode).
 */
export async function syncComments(
  userId: string,
  options: { pageIdOrId?: string; postLimit?: number; commentLimit?: number } = {},
) {
  const { pageIdOrId, postLimit = 10, commentLimit = 50 } = options;

  const pages = await prisma.facebookPage.findMany({
    where: {
      userId,
      isConnected: true,
      ...(pageIdOrId
        ? { OR: [{ id: pageIdOrId }, { pageId: pageIdOrId }] }
        : {}),
    },
  });

  if (pages.length === 0) {
    throw new NotFoundError("No connected Facebook page found");
  }

  const results = [];

  for (const page of pages) {
    const result: {
      pageId: string;
      pageName: string;
      fetched: number;
      imported: number;
      processed: number;
      error?: string;
    } = {
      pageId: page.pageId,
      pageName: page.pageName,
      fetched: 0,
      imported: 0,
      processed: 0,
    };

    try {
      const response = await axios.get(
        `https://graph.facebook.com/v18.0/${page.pageId}/posts`,
        {
          params: {
            fields: `id,created_time,comments.limit(${commentLimit}){id,message,created_time,from}`,
            limit: postLimit,
            access_token: page.pageAccessToken,
          },
        },
      );

      const posts: any[] = response.data?.data ?? [];

      for (const post of posts) {
        const comments: any[] = post.comments?.data ?? [];
        result.fetched += comments.length;

        for (const fbComment of comments) {
          if (!fbComment.message || !fbComment.id) {
            continue;
          }

          // Never ingest the page's own comments — they would trigger replies to ourselves
          if (String(fbComment.from?.id ?? "") === String(page.pageId)) {
            continue;
          }

          const stored = await storeNewComment({
            commentId: fbComment.id,
            facebookPageId: page.id,
            postId: post.id,
            authorId: fbComment.from?.id ?? null,
            authorName: fbComment.from?.name ?? null,
            message: fbComment.message,
            createdTime: fbComment.created_time
              ? new Date(fbComment.created_time)
              : new Date(),
          });

          if (!stored) {
            continue;
          }

          result.imported += 1;

          try {
            await processComment(stored.id);
            result.processed += 1;
          } catch (error) {
            logger.error(
              { error, commentId: stored.id },
              "Synced comment processing failed",
            );
          }
        }
      }
    } catch (error: any) {
      result.error =
        error?.response?.data?.error?.message ||
        error?.message ||
        "Failed to fetch comments from Facebook";
      logger.error(
        { error: error?.response?.data || error?.message, pageId: page.pageId },
        "Comment sync failed for page",
      );
    }

    results.push(result);
  }

  logger.info({ userId, results }, "Comment sync finished");

  return { pages: results };
}

export async function processComment(commentId: string) {
  const comment = await prisma.comment.findUnique({
    where: { id: commentId },
    include: {
      facebookPage: true,
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  // Check if comment is already processed
  if (comment.status !== "PENDING") {
    logger.info(
      { commentId, status: comment.status },
      "Comment already processed",
    );
    return comment;
  }

  // Get AI settings for the user (or create defaults)
  let aiSettings = await prisma.aISettings.findUnique({
    where: { userId: comment.facebookPage.userId },
  });

  if (!aiSettings) {
    aiSettings = await prisma.aISettings.create({
      data: {
        userId: comment.facebookPage.userId,
        status: "ACTIVE",
        aiProvider: "openrouter",
        model: "google/gemma-4-31b-it:free",
        confidenceThreshold: 0.7,
        tone: "professional",
        language: "en",
        emojiUsage: true,
        maxLength: 500,
        spamHandling: "ignore",
        humanApprovalMode: false,
        fallbackBehavior: "skip",
      },
    });
    logger.info({ userId: comment.facebookPage.userId }, "Created default AI settings");
  }

  if (aiSettings.status !== "ACTIVE") {
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "IGNORED" },
    });
    logger.info({ commentId }, "AI not enabled, comment ignored");
    return comment;
  }

  try {
    // 1. Check custom reply rules first
    const matchingRule = await evaluateRules(
      comment.userMessage,
      comment.facebookPage.userId,
    );

    if (matchingRule) {
      logger.info(
        { commentId, ruleId: matchingRule.id, action: matchingRule.action },
        "Matching rule found for comment",
      );

      if (matchingRule.action === "IGNORE") {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "IGNORED" },
        });
        return comment;
      }
    }

    // 2. Analyze comment with AI
    const analysis = await analyzeComment(comment.userMessage, aiSettings);

    // Update comment with AI analysis
    await prisma.comment.update({
      where: { id: commentId },
      data: {
        aiIntent: analysis.intent,
        aiSentiment: analysis.sentiment,
        aiLanguage: analysis.language,
        aiIsSpam: analysis.isSpam,
        aiConfidence: analysis.confidence,
        aiRequiresReview: analysis.requiresHumanReview,
      },
    });

    // 3. Check spam handling
    if (analysis.isSpam && aiSettings.spamHandling === "ignore") {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "IGNORED" },
      });
      logger.info({ commentId }, "Spam detected, comment ignored");
      return comment;
    }

    // 4. Determine reply text (custom rule or AI generation)
    let replyText = "";
    let replyConfidence = analysis.confidence;
    let ruleId: string | null = null;

    if (
      matchingRule &&
      matchingRule.action === "REPLY_CUSTOM" &&
      matchingRule.customReply
    ) {
      replyText = matchingRule.customReply;
      ruleId = matchingRule.id;
      replyConfidence = 1.0;
    } else {
      // Generate reply with AI
      const replyResult = await generateReply(
        comment.userMessage,
        analysis,
        aiSettings,
      );

      // Validate reply
      const isValid = await validateReply(replyResult.reply, aiSettings);
      if (!isValid) {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "ERROR" },
        });
        logger.error({ commentId }, "Generated reply failed validation");
        return comment;
      }

      replyText = replyResult.reply;
      replyConfidence = replyResult.confidence;
    }

    // 5. Determine if human review is required
    // When humanApprovalMode is false (auto-reply ON), the user has explicitly chosen
    // to auto-reply. Only a manually-configured HUMAN_REVIEW rule or spam-review setting
    // can override this — the AI's own requiresHumanReview flag should NOT silently
    // block auto-replies when the user has turned auto-reply ON.
    let requiresReview = false;
    if (aiSettings.humanApprovalMode) {
      // User explicitly configured "Require Human Review" in Settings — always respect this
      requiresReview = true;
    } else if (matchingRule?.action === "HUMAN_REVIEW") {
      // A configured rule explicitly triggered human review
      requiresReview = true;
    } else if (analysis.isSpam && aiSettings.spamHandling === "review") {
      // Spam handling set to review (not ignore) — queue for review
      requiresReview = true;
    }
    // NOTE: We intentionally do NOT block auto-reply based on analysis.requiresHumanReview
    // alone when humanApprovalMode is false. The user's explicit auto-reply preference wins.

    // 6. Create reply record
    const reply = await prisma.reply.create({
      data: {
        commentId: comment.id,
        facebookPageId: comment.facebookPageId,
        generatedReply: replyText,
        status: requiresReview ? "PENDING" : "APPROVED",
        aiProvider: aiSettings.aiProvider,
        ruleId,
        confidence: replyConfidence,
        requiresHumanReview: requiresReview,
      },
    });

    logger.info(
      { commentId, replyId: reply.id, requiresReview },
      "Reply created in database",
    );

    // 7. Auto-reply to Facebook if human review is NOT required
    if (!requiresReview) {
      try {
        await sendReplyToFacebook(reply.id);
        logger.info(
          { commentId, replyId: reply.id },
          "Auto-reply sent directly to Facebook!",
        );
      } catch (sendError) {
        logger.error(
          { error: sendError, commentId, replyId: reply.id },
          "Auto-reply Facebook send failed",
        );
      }
    } else {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "PENDING" },
      });
      logger.info(
        { commentId, replyId: reply.id },
        "Reply queued for human review in dashboard",
      );
    }

    return comment;
  } catch (error) {
    logger.error({ error, commentId }, "Comment processing failed");
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "ERROR" },
    });
    throw error;
  }
}
